// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3qUPj3eEwLcPnOngYv7DCtVF0DZATJdQ',
    appId: '1:242091814600:web:19e84d139121aea749fffd',
    messagingSenderId: '242091814600',
    projectId: 'jalsanrakshan',
    authDomain: 'jalsanrakshan.firebaseapp.com',
    databaseURL: 'https://jalsanrakshan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jalsanrakshan.appspot.com',
    measurementId: 'G-R6G1YCWCMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeYvpzc9WImz3JYWnfTN8l257IwATg7Ec',
    appId: '1:242091814600:android:199cfe90ce66e61849fffd',
    messagingSenderId: '242091814600',
    projectId: 'jalsanrakshan',
    databaseURL: 'https://jalsanrakshan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jalsanrakshan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Wh7rfl63axzOM3I2IDkf2HVRAKd2xJk',
    appId: '1:242091814600:ios:743ab47dd7eed7ac49fffd',
    messagingSenderId: '242091814600',
    projectId: 'jalsanrakshan',
    databaseURL: 'https://jalsanrakshan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jalsanrakshan.appspot.com',
    androidClientId: '242091814600-76cv4nm0cf0gg5ia95ak9g60eeje7ns4.apps.googleusercontent.com',
    iosClientId: '242091814600-u99l5tl8f4qfsd9te7ln2euh1m1gol9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Wh7rfl63axzOM3I2IDkf2HVRAKd2xJk',
    appId: '1:242091814600:ios:543d3d338aba9f3049fffd',
    messagingSenderId: '242091814600',
    projectId: 'jalsanrakshan',
    databaseURL: 'https://jalsanrakshan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jalsanrakshan.appspot.com',
    androidClientId: '242091814600-76cv4nm0cf0gg5ia95ak9g60eeje7ns4.apps.googleusercontent.com',
    iosClientId: '242091814600-8uvbst1dh1aoejurjj0osc6pivfebsvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project4.RunnerTests',
  );
}
